/*
 No Auth - No Cred means no username & password
 Basic Auth/Preemptive Auth - Which needs Username & Password
 Bearer Token Auth 
 API key authentication
*/

import { test, expect } from '@playwright/test'

//No Auth
test("Public API - No Auth", async ({ request }) => {

    const response = await request.get("https://jsonplaceholder.typicode.com/posts/1");

    expect(response.ok()).toBeTruthy();
    const responseBody = await response.json();
    console.log("No Auth Response Body is ======> ", responseBody);
})

//Basic Auth
test("Basic Auth", async ({ request }) => {

    const response = await request.get("https://httpbin.org/basic-auth/user/pass", {
        headers: {
            Authorization: `Basic ` + Buffer.from('user:pass').toString('base64')

        }
    });

    expect(response.ok()).toBeTruthy();
    expect(response.status()).toBe(200);
    const responseBody = await response.json();
    console.log("Basic Auth Response Body is ======> ", responseBody);
})


//Token Auth
//1
test("Token Auth", async ({ request }) => {

    const bearertoken = "github token";
    const response = await request.get("https://api.github.com/user/repos", { // repos generated by particular user
        headers: {
            Authorization: `Bearer ${bearertoken}`

        }
    });

    expect(response.ok()).toBeTruthy();
    expect(response.status()).toBe(200);
    const responseBody = await response.json();
    console.log("Bearer Token Response Body is ======> ", responseBody);
})

//Token Auth
//2
test("Token Auth2", async ({ request }) => {

    const bearertoken = "github token";
    const response = await request.get("https://api.github.com/user", { // repos generated by particular user
        headers: {
            Authorization: `Bearer ${bearertoken}`

        }
    });

    expect(response.ok()).toBeTruthy();
    expect(response.status()).toBe(200);
    const responseBody = await response.json();
    console.log("Bearer Token Response Body is ======> ", responseBody);
})

//API Key Auth - Mostly these are related to query parameter. So, we need to pass them through params option
test("API Key Auth1", async ({ request }) => {

    const response = await request.get("https://openweathermap.org/", {
        params: {
            q: "Hyderabad", //q is the parameter given by developers, where we need to use that
            appid: "GENERATEDAPIKEY" // appid is the API key need to provide, which was specified by dev team. It differs
        }
    });

    expect(response.ok()).toBeTruthy();
    expect(response.status()).toBe(200);
    const responseBody = response.json();
    console.log("API Key Response is ======>", responseBody);


})
